main: main.cpp process.cpp requests.cpp ready_que.cpp fcfs_que.cpp scheduler.cpp scheduler_stats.cpp
	g++ -o main main.cpp process.cpp requests.cpp ready_que.cpp fcfs_que.cpp scheduler.cpp scheduler_stats.cpp
